version: '3'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: splitexpenses
      POSTGRES_USER: splitexpenses
      POSTGRES_PASSWORD: splitexpenses
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
