name: Backend Deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Gradle
      run: cd backend && ./gradlew build -x test
      
    - name: Build Docker image
      run: cd backend && docker build -t split-expenses-backend:latest .
      
    - name: Save Docker image
      run: docker save split-expenses-backend:latest | gzip > split-expenses-backend.tar.gz
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-docker-image
        path: split-expenses-backend.tar.gz
      
    # В будущем здесь может быть добавлен деплой на сервер
