name: Telegram Bot Check

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'telegram-bot/**'
      - '.github/workflows/telegram-*.yml'
      - 'settings.gradle.kts'
      - 'gradle.properties'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'telegram-bot/**'
      - '.github/workflows/telegram-*.yml'
      - 'settings.gradle.kts'
      - 'gradle.properties'

jobs:
  telegram-bot-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Общий кэш для всех модулей
      - name: Setup Common Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-common-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'settings.gradle.kts', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-common-

      # Специфичный кэш для бота
      - name: Setup Android Cache
        uses: actions/cache@v3
        with:
          path: |
            telegram-bot/.gradle
            telegram-bot/build
          key: ${{ runner.os }}-gradle-telegram-bot-${{ hashFiles('telegram-bot/**/*.gradle*') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-telegram-bot-${{ hashFiles('telegram-bot/**/*.gradle*') }}-
            ${{ runner.os }}-gradle-telegram-bot-

      - name: Grant execute permission for gradlew
        run: chmod +x ./telegram-bot/gradlew

      - name: Run ktlint
        run: cd telegram-bot && ./gradlew ktlintCheck

      - name: Run tests
        run: cd telegram-bot && ./gradlew test
